name: girix_code_gauge
description: "A Flutter package for drawing custom shapes and gauges."
version: 0.0.4
homepage: "https://github.com/GirixCode/girix-code-gauge"
repository: "https://github.com/GirixCode/girix-code-gauge"
issue_tracker: "https://github.com/GirixCode/girix-code-gauge/issues"
documentation: "https://github.com/GirixCode/girix-code-gauge?tab=readme-ov-file#girix-code-gauge"
platforms:
  android:
  ios:
  web:
topics:
  - flutter-linear-gauge
  - flutter-radial-gauge
  - flutter-gauge
  - progress-indicator
  - steppers

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
