name: girix_shape
description: "A Flutter package for drawing custom shapes and gauges."
version: 0.0.1
homepage: "https://github.com/mjfoxena/girix-shape.git"
author: "Mrutyunjaya Giri <mrutyunjaya@foxena.com>"

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
